<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcHeRTR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcHeRTR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcHeRTR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcHeRTR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAcHeRTR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AcHeRTR',
    'container.build_id' => '846eadc8',
    'container.build_time' => 1565187372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcHeRTR');
