<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0VfKA5y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0VfKA5y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0VfKA5y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0VfKA5y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0VfKA5y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0VfKA5y',
    'container.build_id' => '1587658f',
    'container.build_time' => 1565639918,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0VfKA5y');
